# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
            always_run: true
            exclude: "migrations/.*"

          - id: end-of-file-fixer
            always_run: true
            exclude: "migrations/.*"

          - id: check-yaml
            always_run: true
            exclude: "migrations/.*"

          - id: check-added-large-files
            always_run: true
            exclude: "migrations/.*"

          - id: check-merge-conflict
            always_run: true
            exclude: "migrations/.*"

    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.4.0
      hooks:
        - id: detect-secrets
          exclude: '^(migrations/.*|alembic\.ini)$'

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.5
      hooks:
          - id: ruff
            always_run: true
            args: [--fix, --config=pyproject.toml]

          - id: ruff-format
